### ISSUE TITLE
how to understand the content of openai.txt ?

### ISSUE THREAD

**Issue by feng-1985** [hwchase17/auto-openai-prompter#1]
Such as what's the meaning of "Open in Playground" ? why need this ?

**Comment by ghost** [comment]
It means you need to use OpenAI's "Playground". It is an interactive environment to test and tune Assistants, Agents, or Chatbots. 

It allows for instruction prompting, interaction with multiple models, and tools such as: a code interpreter, function implementations, and file retrieval.

Get to know it a little better at:
[OpenAI playground](https://platform.openai.com/playground)

**Comment by feng-1985** [comment]
Thanks !
